export const BookingOrderHearders = [
  "Sr.No",
  "ITEMCODE",
  "LOT NO",
  "DISCRIPTION",
  "GROSS WT.",
  "RENTAL START DATE",
  "NO.OF DAYS",
  "BASE PRICE",
  "BOOKING CHARGES",
  "OTHER CHARGES",
  "DISCOUNT",
  "NET CHARGES",
  "SGST",
  "CGST",
  "TOTAL",
];
export const CancelPdfHeders = [
  "SR.No",
  "ITEMCODE",
  "LOT NO",
  "DESCRIPTIONS",
  "GROSS WT",
  "NUMBER OF DAYS",
  "BASE PRICE",
  "BOOKING CHARGES COLLECTED",
  "CANCELLATION CHARGES[SAC - 999794]",
  "OTHER CHARGES",
  "TOTAL CHARGES",
];

export const ServiveInvoicePdfHeaders = [
  "S.No",
  "ITEMCODE",
  "LOT NO",
  "DESCRIPTIONS",
  "GROSS WT",
  "NUMBER OF DAYS RENTED",
  "BASE PRICE",
  "RENTAL CHARGES[SAC - 997329]",
  "LATE FEE[SAC - 999799]",
  "DAMAGE CHARGES[SAC - 999794]",
  "DISCOUNT",
  "TOTAL CHARGES",
  "SGST[9%]",
  "CGST[9%]",
  "TOTAL",
];

export const DeliveryListHearders = [
  "SR.NO",
  "ITEMCODE",
  "LOT NO",
  "DESCRIPTION",
  "GROSS WT.",
  "GROSS WT AT DELIVERY",
  "NUMBER OF DAYS",
  "BASE PRICE",
  "DAMAGE PROTECTION AMOUNT",
];

export const AcknowledgementHeader = [
  "SR.No",
  "ITEMCODE",
  "LOT NO",
  "DESCRIPTIONS",
  "GROSS WT",
  "BASE PRICE",
  "DELIVERY DATE",
  "RETURN DATE",
  "GROSS WT AT DELIVERY",
  "GROSS WT AT RETURN",
  "NUMBER OF DAYS RENTED",
  "PHYSICAL DAMAGE (Y/N)",
];
