export const BookingOrderHearders = [
  "Sr.No",
  "ITEMCODE",
  "LOT NO",
  "DISCRIPTION",
  "GROSS WT.",
  "RENTAL START DATE",
  "BASE PRICE",
  "NO.OF DAYS",
  "BOOKING CHARGES",
  "OTHER CHARGES",
  "DISCOUNT",
  "NET CHARGES",
  "SGST",
  "CGST",
  "TOTAL",
];
